/* price: 1 = under $6 · 2 = $6–12 · 3 = over $12 (data only, not shown)
   iconic: curator's pick · colors: [label background, label ink] */

window.SPECIES = {
  sardine:   { label: "Sardines" },
  anchovy:   { label: "Anchovies" },
  tuna:      { label: "Tuna" },
  mackerel:  { label: "Mackerel" },
  herring:   { label: "Herring" },
  octopus:   { label: "Octopus" },
  squid:     { label: "Squid" },
  mussel:    { label: "Mussels" },
  cockle:    { label: "Cockles" },
  clam:      { label: "Clams" },
  razorclam: { label: "Razor clams" },
  scallop:   { label: "Scallops" },
  oyster:    { label: "Oysters" },
  salmon:    { label: "Salmon" },
  trout:     { label: "Trout" },
  sprat:     { label: "Sprats" },
  cod:       { label: "Cod" },
  urchin:    { label: "Sea urchin" },
  garfish:   { label: "Garfish" },
  eel:       { label: "Eels" },
};

window.COUNTRIES = {
  PT: "Portugal", ES: "Spain", FR: "France", IT: "Italy",
  DK: "Denmark", NO: "Norway", IS: "Iceland", UK: "United Kingdom",
  US: "United States", CA: "Canada", JP: "Japan", MA: "Morocco",
  DE: "Germany", LV: "Latvia", GR: "Greece", TR: "Turkey",
  MX: "Mexico", GH: "Ghana", ZA: "South Africa", PH: "Philippines",
  MY: "Malaysia", KR: "South Korea", AU: "Australia", NZ: "New Zealand",
  HR: "Croatia",
};

window.TINS = [
  {
    id: "nuri-olive", brand: "Nuri", name: "Sardines in Olive Oil", iconic: true,
    species: "sardine", cc: "PT", medium: "olive oil", price: 2,
    tags: ["classic", "rich"],
    note: "Hand-packed at the Pinhais cannery in Matosinhos since 1920 — plump, mild, and the gateway tin for many a conservas convert.",
    pairing: "Buttered sourdough, lemon, flaky salt.",
    colors: ["#C0392B", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "nuri-spiced", brand: "Nuri", name: "Spiced Sardines in Olive Oil",
    species: "sardine", cc: "PT", medium: "spiced olive oil", price: 2,
    tags: ["spicy", "classic"],
    note: "The classic Nuri tin with piri-piri heat, plus a whole carrot, cucumber and clove bobbing inside the can.",
    pairing: "Cold lager and potato chips.",
    colors: ["#B4552D", "#F4E8D0"], pattern: "dots",
  },
  {
    id: "pinhais-tomato", brand: "Pinhais", name: "Sardines in Tomato Sauce",
    species: "sardine", cc: "PT", medium: "tomato sauce", price: 2,
    tags: ["bright", "classic"],
    note: "The same century-old Matosinhos cannery as Nuri, wearing its own family name and a bright, sweet tomato sauce.",
    pairing: "Crusty bread to mop the sauce.",
    colors: ["#1F3A5F", "#E8B54A"], pattern: "stripes",
  },
  {
    id: "berthe-olive", brand: "Berthe", name: "Sardines in Olive Oil",
    species: "sardine", cc: "PT", medium: "olive oil", price: 2,
    tags: ["classic", "clean"],
    note: "A Ramirez-family label with a handsome sailor on the tin; firm fish in golden oil.",
    pairing: "A simple tomato salad.",
    colors: ["#2F6F6B", "#F4E8D0"], pattern: "waves",
  },
  {
    id: "jose-olive", brand: "José Gourmet", name: "Sardines in Olive Oil",
    species: "sardine", cc: "PT", medium: "olive oil", price: 2,
    tags: ["classic", "delicate"],
    note: "Lisbon's design darling — illustrated labels outside, honest Portuguese sardines inside. A taste-test darling for good reason.",
    pairing: "A seacuterie board with pickles and cheese.",
    colors: ["#F1E5C8", "#22333B"], pattern: "dots",
  },
  {
    id: "atimanel-garfish", brand: "Ati Manel", name: "Garfish in Olive Oil",
    species: "garfish", cc: "PT", medium: "olive oil", price: 2,
    tags: ["delicate", "sweet"],
    note: "The needle-nosed agulha, revived by a great-grandson resurrecting his ancestor's 1922 cannery. Delicate and faintly sweet.",
    pairing: "Buttered toast, nothing else.",
    colors: ["#D9A441", "#22333B"], pattern: "diag",
  },
  {
    id: "tricana-olive", brand: "Tricana", name: "Sardines in Olive Oil",
    species: "sardine", cc: "PT", medium: "olive oil", price: 2,
    tags: ["classic", "rich"],
    note: "The house brand of Lisbon's Conserveira de Lisboa, where tins still get wrapped in paper at the counter, as since 1920.",
    pairing: "A glass of vinho verde.",
    colors: ["#2E6E4F", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "lagondola-olive", brand: "La Gondola", name: "Sardines in Olive Oil",
    species: "sardine", cc: "PT", medium: "olive oil", price: 2,
    tags: ["clean", "delicate"],
    note: "Small-batch sardines from a family cannery, prized by tin hunters for their clean, buttery texture.",
    pairing: "Shaved fennel and orange.",
    colors: ["#2B5C8A", "#F4E8D0"], pattern: "waves",
  },
  {
    id: "minerva-olive", brand: "Minerva", name: "Sardines in Olive Oil",
    species: "sardine", cc: "PT", medium: "olive oil", price: 2,
    tags: ["rich", "bold"],
    note: "A Póvoa de Varzim institution with a red-lipped pin-up on the label and reliably meaty fish within.",
    pairing: "Straight from the tin, standing up.",
    colors: ["#B4552D", "#F4E8D0"], pattern: "plain",
  },
  {
    id: "briosa-olive", brand: "Briosa", name: "Sardines in Olive Oil",
    species: "sardine", cc: "PT", medium: "olive oil", price: 2,
    tags: ["briny", "bright"],
    note: "From Figueira da Foz, tinned within hours of the boats landing. Bright, briny, and beautiful.",
    pairing: "Grilled bread rubbed with garlic.",
    colors: ["#E07856", "#22333B"], pattern: "dots",
  },
  {
    id: "porthos-tomato", brand: "Porthos", name: "Sardines in Tomato Sauce",
    species: "sardine", cc: "PT", medium: "tomato sauce", price: 1,
    tags: ["classic", "bright"],
    note: "A century-old Olhão cannery beloved across the Mediterranean for its rich tomato gravy.",
    pairing: "Over rice with a fried egg.",
    colors: ["#3E6E8E", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "damorgada-olive", brand: "Da Morgada", name: "Sardines in Olive Oil",
    species: "sardine", cc: "PT", medium: "olive oil", price: 1,
    tags: ["classic", "clean"],
    note: "An old-guard Portuguese label — firm, silvery fish at a friendly price.",
    pairing: "Chopped into a tomato salad.",
    colors: ["#4A7A4F", "#F4E8D0"], pattern: "plain",
  },
  {
    id: "manna-tomato", brand: "Manná", name: "Sardines in Tomato Sauce",
    species: "sardine", cc: "PT", medium: "tomato sauce", price: 1,
    tags: ["classic", "sweet"],
    note: "The tin every Portuguese kid grew up with; pure comfort food since 1899.",
    pairing: "Buttered toast, after-school energy.",
    colors: ["#E3B23C", "#22333B"], pattern: "stripes",
  },
  {
    id: "santacatarina-tuna", brand: "Santa Catarina", name: "Tuna Fillets in Olive Oil",
    species: "tuna", cc: "PT", medium: "olive oil", price: 2,
    tags: ["clean", "rich"],
    note: "Pole-and-line skipjack from the Azores, cooked whole and hand-filleted on the island of São Jorge.",
    pairing: "White beans, shaved onion, parsley.",
    colors: ["#1F3A5F", "#F4E8D0"], pattern: "waves",
  },
  {
    id: "tenorio-tuna", brand: "Tenório", name: "Tuna Fillets in Olive Oil",
    species: "tuna", cc: "PT", medium: "olive oil", price: 2,
    tags: ["rich", "bold"],
    note: "The other Azorean great — meaty fillets that eat more like steak than tuna.",
    pairing: "A squirt of lemon and good bread.",
    colors: ["#C0392B", "#F4E8D0"], pattern: "plain",
  },
  {
    id: "maria-mackerel", brand: "Maria Organic", name: "Mackerel Fillets in Olive Oil",
    species: "mackerel", cc: "PT", medium: "olive oil", price: 2,
    tags: ["rich", "clean"],
    note: "Certified-organic Portuguese mackerel — rich, omega-packed, and gentler than you fear.",
    pairing: "Rye crackers and crème fraîche.",
    colors: ["#6B7F3A", "#F4E8D0"], pattern: "dots",
  },
  {
    id: "bela-water", brand: "Bela", name: "Sardines in Spring Water",
    species: "sardine", cc: "PT", medium: "spring water", price: 2,
    tags: ["clean", "delicate"],
    note: "From Olhão, packed in nothing but spring water — the purist's sardine, all clean fish flavor.",
    pairing: "A drizzle of your best olive oil.",
    colors: ["#7FA8C9", "#22333B"], pattern: "waves",
  },
  {
    id: "ramirez-olive", brand: "Ramirez", name: "Sardines in Olive Oil",
    species: "sardine", cc: "PT", medium: "olive oil", price: 1,
    tags: ["classic", "briny"],
    note: "From Portugal's oldest cannery, founded 1853 — the house that basically invented the category.",
    pairing: "History, with bread.",
    colors: ["#8E2F23", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "ortiz-bonito", brand: "Ortiz", name: "Bonito del Norte in Olive Oil", iconic: true,
    species: "tuna", cc: "ES", medium: "olive oil", price: 2,
    tags: ["clean", "delicate"],
    note: "Line-caught Basque albacore, poached and packed in olive oil. The white tuna that ruins all other tuna.",
    pairing: "Pintxo-style on bread with a piquillo pepper.",
    colors: ["#F1E5C8", "#C0392B"], pattern: "plain",
  },
  {
    id: "ortiz-anchovy", brand: "Ortiz", name: "Anchovies in Olive Oil", iconic: true,
    species: "anchovy", cc: "ES", medium: "olive oil", price: 2,
    tags: ["briny", "bold"],
    note: "Cantabrian anchovies cured in salt and filleted by hand — deep, savory, dangerously snackable.",
    pairing: "Tomato-rubbed toast.",
    colors: ["#F1E5C8", "#22333B"], pattern: "stripes",
  },
  {
    id: "ramonpena-sardine", brand: "Ramón Peña", name: "Small Sardines in Olive Oil", iconic: true,
    species: "sardine", cc: "ES", medium: "olive oil", price: 3,
    tags: ["delicate", "decadent"],
    note: "Galicia's gold standard: tiny, silvery sardinillas arranged like jewelry. The tin people photograph.",
    pairing: "Kettle chips and fino sherry.",
    colors: ["#1E1E24", "#D9A441"], pattern: "plain",
  },
  {
    id: "ramonpena-squid", brand: "Ramón Peña", name: "Squid in Its Own Ink",
    species: "squid", cc: "ES", medium: "its own ink", price: 2,
    tags: ["briny", "bold"],
    note: "Tender squid bathed in jet-black ink sauce — dramatic, briny, unforgettable.",
    pairing: "White rice to catch the ink.",
    colors: ["#22333B", "#7FA8C9"], pattern: "waves",
  },
  {
    id: "ramonpena-octopus", brand: "Ramón Peña", name: "Octopus in Olive Oil",
    species: "octopus", cc: "ES", medium: "olive oil", price: 3,
    tags: ["rich", "clean"],
    note: "Coins of tender octopus in golden oil — pulpo a feira straight from a tin.",
    pairing: "Smoked paprika and boiled potatoes.",
    colors: ["#1E1E24", "#E07856"], pattern: "dots",
  },
  {
    id: "cambados-mussels", brand: "Conservas de Cambados", name: "Mussels in Escabeche",
    species: "mussel", cc: "ES", medium: "escabeche", price: 2,
    tags: ["bright", "briny"],
    note: "Plump Galician mussels in a paprika-laced vinegar marinade. The benchmark escabeche.",
    pairing: "Chips, toothpicks, cold vermouth.",
    colors: ["#274C77", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "cambados-urchin", brand: "Conservas de Cambados", name: "Sea Urchin Roe",
    species: "urchin", cc: "ES", medium: "brine", price: 3,
    tags: ["sweet", "decadent"],
    note: "Erizo de mar — sweet, oceanic custard spooned from Galician urchins. A tiny tin of luxury.",
    pairing: "A spoon. Maybe a blini.",
    colors: ["#6E3B5C", "#E8B54A"], pattern: "dots",
  },
  {
    id: "labrujula-sardine", brand: "La Brújula", name: "Sardines in Olive Oil",
    species: "sardine", cc: "ES", medium: "olive oil", price: 2,
    tags: ["classic", "clean"],
    note: "Hand-packed in A Coruña under a compass-rose label; consistently among Spain's best-value tins.",
    pairing: "Pan con tomate.",
    colors: ["#2F7E7B", "#F4E8D0"], pattern: "waves",
  },
  {
    id: "labrujula-razor", brand: "La Brújula", name: "Razor Clams in Brine",
    species: "razorclam", cc: "ES", medium: "brine", price: 3,
    tags: ["sweet", "delicate"],
    note: "Navajas — sweet, snappy razor clams in clean brine. They taste like the tide coming in.",
    pairing: "Just lemon and a fork.",
    colors: ["#2F7E7B", "#E8B54A"], pattern: "diag",
  },
  {
    id: "gueyumar-sardine", brand: "Güeyu Mar", name: "Chargrilled Sardines", iconic: true,
    species: "sardine", cc: "ES", medium: "olive oil", price: 3,
    tags: ["smoky", "decadent"],
    note: "Chef Abel Álvarez grills Asturian sardines over birchwood before tinning. Smoke, char, genius.",
    pairing: "Good bread and silence.",
    colors: ["#2B2B2B", "#E2703A"], pattern: "plain",
  },
  {
    id: "gueyumar-octopus", brand: "Güeyu Mar", name: "Chargrilled Octopus",
    species: "octopus", cc: "ES", medium: "olive oil", price: 3,
    tags: ["smoky", "decadent"],
    note: "Octopus kissed by the same birchwood grill — the tin that converts skeptics at dinner parties.",
    pairing: "Crusty bread, fruity olive oil.",
    colors: ["#2B2B2B", "#D9A441"], pattern: "stripes",
  },
  {
    id: "realconservera-sardine", brand: "Real Conservera Española", name: "Small Sardines in Olive Oil",
    species: "sardine", cc: "ES", medium: "olive oil", price: 3,
    tags: ["delicate", "classic"],
    note: "From Cambados, routinely atop Spanish rankings — meticulous fish, museum-grade labels.",
    pairing: "A cold manzanilla.",
    colors: ["#7A2E3A", "#E8B54A"], pattern: "plain",
  },
  {
    id: "peperetes-cockles", brand: "Los Peperetes", name: "Cockles in Brine", iconic: true,
    species: "cockle", cc: "ES", medium: "brine", price: 3,
    tags: ["sweet", "briny"],
    note: "Berberechos from the Rías Baixas, washed thirty times and packed by hand. Sweet little ocean candies.",
    pairing: "Vermouth, orange slice, olive.",
    colors: ["#C0392B", "#F4E8D0"], pattern: "dots",
  },
  {
    id: "peperetes-scallops", brand: "Los Peperetes", name: "Scallops in Vieira Sauce",
    species: "scallop", cc: "ES", medium: "vieira sauce", price: 3,
    tags: ["rich", "sweet"],
    note: "Zamburiñas in a slow-cooked tomato-and-onion vieira sauce — Galicia's holiday tin.",
    pairing: "Bread for the sauce, first and always.",
    colors: ["#B4552D", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "espinaler-mussels", brand: "Espinaler", name: "Mussels in Escabeche",
    species: "mussel", cc: "ES", medium: "escabeche", price: 2,
    tags: ["bright", "classic"],
    note: "From the Vilassar de Mar tavern that made escabeche famous — don't forget their bottled sauce.",
    pairing: "The full Espinaler aperitif: chips, olives, vermouth.",
    colors: ["#C0392B", "#F1E5C8"], pattern: "plain",
  },
  {
    id: "espinaler-squid", brand: "Espinaler", name: "Baby Squid in Ink",
    species: "squid", cc: "ES", medium: "its own ink", price: 2,
    tags: ["briny", "rich"],
    note: "Chipirones in their own ink — rich, inky, and begging to be piled onto rice.",
    pairing: "Rice, alioli, parsley.",
    colors: ["#22333B", "#F4E8D0"], pattern: "waves",
  },
  {
    id: "yurrita-anchovy", brand: "Yurrita", name: "Anchovies in Olive Oil",
    species: "anchovy", cc: "ES", medium: "olive oil", price: 2,
    tags: ["briny", "delicate"],
    note: "A Getaria family cannery since 1867; plump fillets with a gentle cure.",
    pairing: "Butter on toast, anchovy on top.",
    colors: ["#E8B54A", "#22333B"], pattern: "stripes",
  },
  {
    id: "olasagasti-anchovy", brand: "Olasagasti", name: "Anchovies à la Basque",
    species: "anchovy", cc: "ES", medium: "olive oil", price: 2,
    tags: ["briny", "spicy"],
    note: "Cantabrian fillets dressed Basque-style with garlic and a whisper of Espelette pepper.",
    pairing: "A cold txakoli.",
    colors: ["#2B5C8A", "#F4E8D0"], pattern: "diag",
  },
  {
    id: "elcapricho-ventresca", brand: "El Capricho", name: "Ventresca de Atún in Olive Oil", iconic: true,
    species: "tuna", cc: "ES", medium: "olive oil", price: 3,
    tags: ["decadent", "rich"],
    note: "Bluefin belly from Barbate's almadraba — buttery, marbled, the wagyu of tinned fish.",
    pairing: "Flaky salt, nothing else.",
    colors: ["#F1E5C8", "#1F3A5F"], pattern: "plain",
  },
  {
    id: "herpac-ventresca", brand: "Herpac", name: "Yellowfin Ventresca in Olive Oil",
    species: "tuna", cc: "ES", medium: "olive oil", price: 3,
    tags: ["decadent", "delicate"],
    note: "Barbate's other temple of tuna; ventresca so soft it practically spreads.",
    pairing: "On warm toast with crushed tomato.",
    colors: ["#1F3A5F", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "matiz-sardine", brand: "Matiz", name: "Sardines in Olive Oil",
    species: "sardine", cc: "ES", medium: "olive oil", price: 1,
    tags: ["classic", "clean"],
    note: "Wild-caught off Galicia and easy to find stateside — a trusty first step into conservas.",
    pairing: "Crackers and hot sauce.",
    colors: ["#3E6E8E", "#F4E8D0"], pattern: "dots",
  },
  {
    id: "lacuriosa-sardine", brand: "La Curiosa", name: "Spicy Small Sardines",
    species: "sardine", cc: "ES", medium: "spiced olive oil", price: 2,
    tags: ["spicy", "bright"],
    note: "A playful new-wave Galician label — sardinillas with a friendly kick of chili.",
    pairing: "Ice-cold beer.",
    colors: ["#E08E9B", "#22333B"], pattern: "diag",
  },
  {
    id: "donostia-sardine", brand: "Donostia", name: "Sardines in Olive Oil",
    species: "sardine", cc: "ES", medium: "olive oil", price: 2,
    tags: ["rich", "bold"],
    note: "Basque Country sardines that topped a 59-tin blind taste test. Plump and pleasantly pungent.",
    pairing: "Pintxos night at home.",
    colors: ["#F1E5C8", "#2E6E4F"], pattern: "stripes",
  },
  {
    id: "labelleiloise-sardine", brand: "La Belle-Iloise", name: "Sardines in Olive Oil",
    species: "sardine", cc: "FR", medium: "olive oil", price: 2,
    tags: ["classic", "rich"],
    note: "Quiberon's beloved cannery since 1932 — sardines aged like wine, best after a year in the tin.",
    pairing: "Salted butter and baguette.",
    colors: ["#B43A2E", "#F4E8D0"], pattern: "plain",
  },
  {
    id: "mouettes-sardine", brand: "Mouettes d'Arvor", name: "Sardines in Extra Virgin Olive Oil",
    species: "sardine", cc: "FR", medium: "olive oil", price: 2,
    tags: ["classic", "delicate"],
    note: "From Conserverie Gonidec, the last cannery in Concarneau — vintage-dated and worthy of it.",
    pairing: "A Breton cider.",
    colors: ["#1F3A5F", "#F4E8D0"], pattern: "waves",
  },
  {
    id: "mouettes-mackerel", brand: "Mouettes d'Arvor", name: "Mackerel Fillets in Muscadet", iconic: true,
    species: "mackerel", cc: "FR", medium: "muscadet wine", price: 2,
    tags: ["delicate", "bright"],
    note: "Brittany mackerel poached in Muscadet with aromatics — elegant and unexpectedly gentle.",
    pairing: "Boiled potatoes and butter.",
    colors: ["#223A5E", "#E8B54A"], pattern: "stripes",
  },
  {
    id: "connetable-sardine", brand: "Connétable", name: "Sardines in Olive Oil", iconic: true,
    species: "sardine", cc: "FR", medium: "olive oil", price: 1,
    tags: ["classic", "briny"],
    note: "The red-label classic, tinned since 1853 — the oldest sardine brand still swimming.",
    pairing: "A picnic, ideally in Brittany.",
    colors: ["#A93226", "#F4E8D0"], pattern: "dots",
  },
  {
    id: "quiberonnaise-sardine", brand: "La Quiberonnaise", name: "Sardines à l'Ancienne",
    species: "sardine", cc: "FR", medium: "olive oil", price: 2,
    tags: ["rich", "bold"],
    note: "Fried before tinning, the old way — deeper flavor, softer bones, cult following.",
    pairing: "Warm baguette, salted butter.",
    colors: ["#F1E5C8", "#1F3A5F"], pattern: "stripes",
  },
  {
    id: "phare-sardine", brand: "Phare d'Eckmühl", name: "Sardines in Organic Olive Oil",
    species: "sardine", cc: "FR", medium: "olive oil", price: 2,
    tags: ["clean", "classic"],
    note: "Brittany sardines in organic oil, named for a lighthouse and packed with Breton pride.",
    pairing: "Sea air, optional.",
    colors: ["#223A5E", "#F4E8D0"], pattern: "plain",
  },
  {
    id: "petitnavire-tuna", brand: "Petit Navire", name: "Yellowfin Tuna in Olive Oil",
    species: "tuna", cc: "FR", medium: "olive oil", price: 1,
    tags: ["classic", "clean"],
    note: "France's everyday icon since 1932 — the tuna of a million French picnics.",
    pairing: "Salade niçoise, naturally.",
    colors: ["#2B5C8A", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "callipo-tuna", brand: "Callipo", name: "Yellowfin Tuna in Olive Oil",
    species: "tuna", cc: "IT", medium: "olive oil", price: 2,
    tags: ["rich", "classic"],
    note: "Calabria's pride since 1913 — solid, rosy fillets that hold their own in any pan bagnat.",
    pairing: "Pan bagnat with all the fixings.",
    colors: ["#E3B23C", "#22333B"], pattern: "plain",
  },
  {
    id: "testa-anchovy", brand: "Testa", name: "Anchovies in Olive Oil",
    species: "anchovy", cc: "IT", medium: "olive oil", price: 2,
    tags: ["briny", "bold"],
    note: "Sicilian anchovies from Sciacca, salted and filleted by a family five generations deep.",
    pairing: "Pasta con le sarde energy.",
    colors: ["#2B5C8A", "#F4E8D0"], pattern: "waves",
  },
  {
    id: "pollastrini-sardine", brand: "Pollastrini", name: "Sardines in Olive Oil",
    species: "sardine", cc: "IT", medium: "olive oil", price: 2,
    tags: ["classic", "rich"],
    note: "Italy's sardine stalwart since 1889 — the country's only major sardine cannery still at it.",
    pairing: "Fennel salad, orange, olives.",
    colors: ["#C0392B", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "riomare-tuna", brand: "Rio Mare", name: "Tuna in Olive Oil", iconic: true,
    species: "tuna", cc: "IT", medium: "olive oil", price: 1,
    tags: ["classic", "clean"],
    note: "Italy's lunchbox legend — the default tuna for a nation of pasta al tonno.",
    pairing: "Pasta al tonno, obviously.",
    colors: ["#2E5FA3", "#F4E8D0"], pattern: "plain",
  },
  {
    id: "asdomar-tuna", brand: "As do Mar", name: "Tuna in Olive Oil",
    species: "tuna", cc: "IT", medium: "olive oil", price: 2,
    tags: ["clean", "delicate"],
    note: "Portuguese-owned, Italian-beloved — firm, clean fillets in good oil.",
    pairing: "Cannellini beans and red onion.",
    colors: ["#B43A2E", "#F4E8D0"], pattern: "dots",
  },
  {
    id: "fangst-brisling", brand: "Fangst", name: "Brisling No. 1 — Smoked Sprats",
    species: "sprat", cc: "DK", medium: "smoked, in rapeseed oil", price: 2,
    tags: ["smoky", "delicate"],
    note: "A Nordic rethink of the Baltic sprat: lightly smoked, packed in cold-pressed rapeseed oil.",
    pairing: "Rye bread, butter, chives.",
    colors: ["#EFE9DC", "#22333B"], pattern: "plain",
  },
  {
    id: "fangst-salmon", brand: "Fangst", name: "Faroe Islands Salmon",
    species: "salmon", cc: "DK", medium: "its own juices", price: 2,
    tags: ["clean", "rich"],
    note: "Faroese salmon tinned with just salt — clean, rich, and very Scandinavian about it.",
    pairing: "Dense rye, pickled cucumber.",
    colors: ["#EFE9DC", "#B4552D"], pattern: "stripes",
  },
  {
    id: "kingoscar-brisling", brand: "King Oscar", name: "Brisling Sardines in Olive Oil", iconic: true,
    species: "sprat", cc: "NO", medium: "olive oil", price: 1,
    tags: ["smoky", "classic"],
    note: "Tiny Norwegian sprats with a royal warrant on the label — the classic sardine of a century of lunchboxes.",
    pairing: "Saltines, like it's 1957.",
    colors: ["#B43A2E", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "lysi-codliver", brand: "Lýsi", name: "Cod Liver in Its Own Oil", iconic: true,
    species: "cod", cc: "IS", medium: "its own oil", price: 1,
    tags: ["decadent", "funky"],
    note: "Iceland's bracing delicacy — foie gras of the sea, packed in its own golden oil.",
    pairing: "Rye crackers and an open mind.",
    colors: ["#3E6E8E", "#F4E8D0"], pattern: "plain",
  },
  {
    id: "fish4ever-skipjack", brand: "Fish4Ever", name: "Skipjack Tuna in Spring Water",
    species: "tuna", cc: "UK", medium: "spring water", price: 2,
    tags: ["clean", "classic"],
    note: "Pole-and-line skipjack from a UK pioneer of sustainable tinned fish.",
    pairing: "A very righteous tuna melt.",
    colors: ["#2E6E63", "#F4E8D0"], pattern: "waves",
  },
  {
    id: "fishwife-trout", brand: "Fishwife", name: "Smoked Rainbow Trout", iconic: true,
    species: "trout", cc: "US", medium: "smoked, in olive oil", price: 2,
    tags: ["smoky", "rich"],
    note: "Idaho trout smoked over applewood — the tin that launched a thousand seacuterie boards.",
    pairing: "Cream cheese, everything seasoning.",
    colors: ["#B4552D", "#F4E8D0"], pattern: "plain",
  },
  {
    id: "fishwife-tuna", brand: "Fishwife", name: "Smoked Albacore Tuna",
    species: "tuna", cc: "US", medium: "smoked, in olive oil", price: 2,
    tags: ["smoky", "rich"],
    note: "Line-caught albacore smoked and packed in olive oil — tuna salad's glow-up.",
    pairing: "The best tuna melt of your life.",
    colors: ["#D98E8E", "#22333B"], pattern: "dots",
  },
  {
    id: "fishwife-sardine", brand: "Fishwife", name: "Sardines with Preserved Lemon",
    species: "sardine", cc: "US", medium: "olive oil", price: 2,
    tags: ["bright", "briny"],
    note: "Cornish sardines brightened with preserved lemon — sunshine in a very giftable tin.",
    pairing: "Sourdough and salted butter.",
    colors: ["#2F7E7B", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "wildplanet-skipjack", brand: "Wild Planet", name: "Skipjack Tuna in Water",
    species: "tuna", cc: "US", medium: "water", price: 1,
    tags: ["clean", "classic"],
    note: "Pole-and-troll caught, cooked once in the can — the sustainable staple of American pantries.",
    pairing: "Weeknight tuna anything.",
    colors: ["#4A7A4F", "#F4E8D0"], pattern: "plain",
  },
  {
    id: "ekone-oyster", brand: "Ekone", name: "Smoked Oysters",
    species: "oyster", cc: "US", medium: "smoked, in oil", price: 2,
    tags: ["smoky", "sweet"],
    note: "Willapa Bay oysters smoked over maple — plump, sweet, campfire-kissed.",
    pairing: "Crackers, hot sauce, cold beer.",
    colors: ["#7A5C3A", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "patagonia-mussels", brand: "Patagonia Provisions", name: "Smoked Mussels",
    species: "mussel", cc: "US", medium: "smoked, in olive oil", price: 2,
    tags: ["smoky", "briny"],
    note: "Galician mussels, lightly smoked — Patagonia's edible argument for thoughtful eating.",
    pairing: "Torn bread and aioli.",
    colors: ["#D97B3A", "#22333B"], pattern: "plain",
  },
  {
    id: "scout-salmon", brand: "Scout", name: "Smoked Wild Pink Salmon",
    species: "salmon", cc: "US", medium: "smoked, in olive oil", price: 2,
    tags: ["smoky", "delicate"],
    note: "Pacific pink salmon, smoked and tinned — a bridge between the canoe and the seacuterie board.",
    pairing: "Bagels, obviously.",
    colors: ["#D98E7A", "#22333B"], pattern: "waves",
  },
  {
    id: "stjeans-salmon", brand: "St. Jean's", name: "Smoked Sockeye Salmon",
    species: "salmon", cc: "CA", medium: "smoked", price: 2,
    tags: ["smoky", "rich"],
    note: "Vancouver Island sockeye smoked the hard way since 1961 — candied edges, deep red flesh.",
    pairing: "Straight from the tin, on a dock.",
    colors: ["#A93226", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "sava-can", brand: "Iwatei", name: "Ça va? Sava Can — Mackerel in Olive Oil", iconic: true,
    species: "mackerel", cc: "JP", medium: "olive oil", price: 1,
    tags: ["clean", "bright"],
    note: "Iwate's stylish answer to canned mackerel, born from post-tsunami recovery. Ten million cans and counting.",
    pairing: "Rice, or the world's best fish sandwich.",
    colors: ["#6B8E4E", "#F4E8D0"], pattern: "dots",
  },
  {
    id: "seachicken", brand: "Hagoromo", name: "Sea Chicken Tuna", iconic: true,
    species: "tuna", cc: "JP", medium: "water", price: 1,
    tags: ["clean", "classic"],
    note: "Japan's beloved tuna since 1958 — the name alone earns it a spot on the shelf.",
    pairing: "Onigiri filling or tuna-mayo toast.",
    colors: ["#7FA8C9", "#22333B"], pattern: "stripes",
  },
  {
    id: "kk-oyster", brand: "K&K", name: "Smoked Oysters (Can Tsuma)",
    species: "oyster", cc: "JP", medium: "smoked, in oil", price: 1,
    tags: ["smoky", "rich"],
    note: "Hiroshima oysters smoked over cherry wood — Japan's favorite beer snack in a can.",
    pairing: "Cold sake or a highball.",
    colors: ["#1E1E24", "#D9A441"], pattern: "plain",
  },
  {
    id: "titus-sardine", brand: "Titus", name: "Sardines in Vegetable Oil", iconic: true,
    species: "sardine", cc: "MA", medium: "vegetable oil", price: 1,
    tags: ["classic", "bold"],
    note: "The Moroccan tin that feeds West Africa — humble, mighty, and in every corner shop from Dakar to Lagos.",
    pairing: "Bread, harissa, and strong tea.",
    colors: ["#C0392B", "#E8B54A"], pattern: "stripes",
  },
  {
    id: "bompetisco-tuna", brand: "Bom Petisco", name: "Tuna Fillets in Olive Oil",
    species: "tuna", cc: "PT", medium: "olive oil", price: 1,
    tags: ["clean", "classic"],
    note: "The Azores' everyday tuna — pole-caught skipjack from the mid-Atlantic, beloved on every island.",
    pairing: "Crusty bread and a cold imperial.",
    colors: ["#2E6E4F", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "minerva-spiced", brand: "Minerva", name: "Spiced Sardines in Olive Oil",
    species: "sardine", cc: "PT", medium: "spiced olive oil", price: 2,
    tags: ["spicy", "rich"],
    note: "Minerva's pin-up label hides a piri-piri kick — a Lisbon tasca favorite.",
    pairing: "Cold vinho verde.",
    colors: ["#8E2F23", "#F4E8D0"], pattern: "dots",
  },
  {
    id: "porthos-olive", brand: "Porthos", name: "Sardines in Olive Oil",
    species: "sardine", cc: "PT", medium: "olive oil", price: 1,
    tags: ["classic", "clean"],
    note: "Olhão's century-old cannery doing the simple thing right.",
    pairing: "Grilled bread, sea salt.",
    colors: ["#274C77", "#F4E8D0"], pattern: "plain",
  },
  {
    id: "calvo-tuna", brand: "Calvo", name: "Atún Claro in Olive Oil",
    species: "tuna", cc: "ES", medium: "olive oil", price: 1,
    tags: ["clean", "classic"],
    note: "Spain's supermarket sovereign — the tuna every Spanish abuela actually buys.",
    pairing: "Ensaladilla rusa.",
    colors: ["#E3B23C", "#22333B"], pattern: "stripes",
  },
  {
    id: "arroyabe-anchovy", brand: "Arroyabe", name: "Anchovies in Olive Oil",
    species: "anchovy", cc: "ES", medium: "olive oil", price: 2,
    tags: ["briny", "delicate"],
    note: "A Bermeo family cannery since 1898 — the Cantabrian anchovy you'll actually find stateside.",
    pairing: "Buttered toast, sliced tomato.",
    colors: ["#2F7E7B", "#F4E8D0"], pattern: "waves",
  },
  {
    id: "ortiz-sardine", brand: "Ortiz", name: "Sardines a la Antigua",
    species: "sardine", cc: "ES", medium: "olive oil", price: 2,
    tags: ["classic", "rich"],
    note: "The Basque masters' take on sardines — old-style, silvery, superb.",
    pairing: "A pintxo with a guindilla pepper.",
    colors: ["#F1E5C8", "#B43A2E"], pattern: "stripes",
  },
  {
    id: "matiz-octopus", brand: "Matiz", name: "Octopus in Olive Oil",
    species: "octopus", cc: "ES", medium: "olive oil", price: 2,
    tags: ["rich", "clean"],
    note: "Galician pulpo from the same folks as the trusty sardines — tender coins ready for paprika.",
    pairing: "Potatoes, pimentón, olive oil.",
    colors: ["#3E6E8E", "#E8B54A"], pattern: "dots",
  },
  {
    id: "espinaler-cockles", brand: "Espinaler", name: "Cockles in Brine",
    species: "cockle", cc: "ES", medium: "brine", price: 2,
    tags: ["sweet", "briny"],
    note: "Berberechos from the tavern that wrote the book on aperitivo hour.",
    pairing: "Vermouth — and Espinaler sauce, if you have it.",
    colors: ["#C0392B", "#F1E5C8"], pattern: "waves",
  },
  {
    id: "cambados-clams", brand: "Conservas de Cambados", name: "Clams in Brine",
    species: "clam", cc: "ES", medium: "brine", price: 3,
    tags: ["sweet", "delicate"],
    note: "Almejas al natural — Galician clams so clean they taste like the ría at low tide.",
    pairing: "A glass of albariño.",
    colors: ["#274C77", "#E8B54A"], pattern: "dots",
  },
  {
    id: "rizzoli-anchovy", brand: "Rizzoli", name: "Anchovies in Olive Oil",
    species: "anchovy", cc: "IT", medium: "olive oil", price: 2,
    tags: ["briny", "rich"],
    note: "Parma's golden tin since 1906 — the anchovy Italians reach for first.",
    pairing: "Butter curls on good bread.",
    colors: ["#D9A441", "#22333B"], pattern: "plain",
  },
  {
    id: "rugen-herring", brand: "Rügen Fisch", name: "Smoked Herring Fillets",
    species: "herring", cc: "DE", medium: "smoked, in oil", price: 1,
    tags: ["smoky", "rich"],
    note: "Germany's cannery workhorse from the Baltic coast — honest smoked herring since 1949.",
    pairing: "Black bread and butter.",
    colors: ["#3E6E8E", "#F4E8D0"], pattern: "waves",
  },
  {
    id: "brivais-sprats", brand: "Brīvais Vilnis", name: "Smoked Sprats in Oil", iconic: true,
    species: "sprat", cc: "LV", medium: "smoked, in oil", price: 1,
    tags: ["smoky", "bold"],
    note: "Riga's legendary sprats — the Soviet-era icon that still rules the rye-bread canapé.",
    pairing: "Rye, butter, sliced egg, dill.",
    colors: ["#8E2F23", "#E8B54A"], pattern: "stripes",
  },
  {
    id: "johnwest-kippers", brand: "John West", name: "Kipper Fillets",
    species: "herring", cc: "UK", medium: "smoked, in oil", price: 1,
    tags: ["smoky", "classic"],
    note: "The British breakfast kipper, tinned — Victorian mornings, modern convenience.",
    pairing: "Toast, butter, a pot of tea.",
    colors: ["#1F3A5F", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "stabburet-mackerel", brand: "Stabburet", name: "Mackerel in Tomato Sauce", iconic: true,
    species: "mackerel", cc: "NO", medium: "tomato sauce", price: 1,
    tags: ["rich", "classic"],
    note: "Makrell i tomat — Norway's national spread, beloved on crispbread and waffles alike.",
    pairing: "Knekkebrød and brown cheese.",
    colors: ["#B43A2E", "#F4E8D0"], pattern: "plain",
  },
  {
    id: "trata-sardine", brand: "Trata", name: "Sardines in Olive Oil",
    species: "sardine", cc: "GR", medium: "olive oil", price: 1,
    tags: ["briny", "classic"],
    note: "Aegean sardines from Greece's best-known cannery — sunny, salty, straightforward.",
    pairing: "Ouzo, olives, tomatoes.",
    colors: ["#2E5FA3", "#F4E8D0"], pattern: "plain",
  },
  {
    id: "dardanel-tuna", brand: "Dardanel", name: "Tuna in Olive Oil",
    species: "tuna", cc: "TR", medium: "olive oil", price: 1,
    tags: ["clean", "classic"],
    note: "Turkey's iconic ton balığı, canned in Çanakkale by the very strait it's named for.",
    pairing: "White beans, red onion, parsley.",
    colors: ["#C0392B", "#F4E8D0"], pattern: "dots",
  },
  {
    id: "crownprince-oyster", brand: "Crown Prince", name: "Smoked Oysters",
    species: "oyster", cc: "US", medium: "smoked, in oil", price: 1,
    tags: ["smoky", "rich"],
    note: "The two-dollar tin that starts the obsession — found in every American grocery store.",
    pairing: "Saltines and hot sauce.",
    colors: ["#7A5C3A", "#F4E8D0"], pattern: "dots",
  },
  {
    id: "barharbor-kipper", brand: "Bar Harbor", name: "Kippered Herring",
    species: "herring", cc: "US", medium: "smoked", price: 1,
    tags: ["smoky", "classic"],
    note: "Downeast Maine's answer to the kipper — smoky, salty, splendid on toast.",
    pairing: "Toast points and red onion.",
    colors: ["#2F6F6B", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "demings-salmon", brand: "Deming's", name: "Wild Alaskan Red Sockeye",
    species: "salmon", cc: "US", medium: "its own juices", price: 1,
    tags: ["rich", "classic"],
    note: "A century of Alaskan canneries in one deep-red tin — bones, history, and all.",
    pairing: "Salmon cakes, or straight with lemon.",
    colors: ["#A93226", "#F4E8D0"], pattern: "plain",
  },
  {
    id: "tinyfish-geoduck", brand: "Tiny Fish Co.", name: "Smoked Geoduck",
    species: "clam", cc: "US", medium: "smoked, in oil", price: 2,
    tags: ["smoky", "sweet"],
    note: "Washington's improbable giant clam, smoked and tinned — sweet, snappy, conversation-starting.",
    pairing: "Crackers and a crisp white.",
    colors: ["#2E6E63", "#E8B54A"], pattern: "diag",
  },
  {
    id: "fishwife-salmon", brand: "Fishwife", name: "Smoked Atlantic Salmon",
    species: "salmon", cc: "US", medium: "smoked", price: 2,
    tags: ["smoky", "delicate"],
    note: "Buttery smoked salmon from the brand that made tinned fish a personality trait.",
    pairing: "Bagel, cream cheese, capers.",
    colors: ["#D98E8E", "#22333B"], pattern: "stripes",
  },
  {
    id: "season-sardine", brand: "Season", name: "Sardines in Olive Oil",
    species: "sardine", cc: "US", medium: "olive oil", price: 1,
    tags: ["classic", "clean"],
    note: "The American supermarket standby — a perfectly respectable weeknight tin.",
    pairing: "Crackers and mustard.",
    colors: ["#2B5C8A", "#F4E8D0"], pattern: "dots",
  },
  {
    id: "genova-tuna", brand: "Genova", name: "Yellowfin Tuna in Olive Oil",
    species: "tuna", cc: "US", medium: "olive oil", price: 1,
    tags: ["clean", "classic"],
    note: "The Italian-style staple of American pantries — a solid Tuesday-night tin.",
    pairing: "Pasta, capers, lemon.",
    colors: ["#E3B23C", "#22333B"], pattern: "plain",
  },
  {
    id: "brunswick-sardine", brand: "Brunswick", name: "Sardines in Soybean Oil",
    species: "sardine", cc: "CA", medium: "vegetable oil", price: 1,
    tags: ["classic", "bold"],
    note: "The Canadian lunchbox classic from New Brunswick — humble, fishy, nostalgic.",
    pairing: "White bread and butter.",
    colors: ["#C8402A", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "dolores-tuna", brand: "Dolores", name: "Yellowfin Tuna in Vegetable Oil",
    species: "tuna", cc: "MX", medium: "vegetable oil", price: 1,
    tags: ["clean", "classic"],
    note: "Mexico's atún of record — the backbone of a million tuna tostadas.",
    pairing: "Tostada, crema, chipotle.",
    colors: ["#2E6E63", "#F4E8D0"], pattern: "waves",
  },
  {
    id: "geisha-mackerel", brand: "Geisha", name: "Mackerel in Tomato Sauce",
    species: "mackerel", cc: "GH", medium: "tomato sauce", price: 1,
    tags: ["rich", "bold"],
    note: "Ask any Ghanaian about Geisha — the mackerel tin that seasons a million stews and jollofs.",
    pairing: "Jollof rice, obviously.",
    colors: ["#B4552D", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "luckystar-pilchards", brand: "Lucky Star", name: "Pilchards in Tomato Sauce",
    species: "sardine", cc: "ZA", medium: "tomato sauce", price: 1,
    tags: ["classic", "bold"],
    note: "South Africa's lunchbox legend — pilchards (which is to say, sardines) in sweet tomato gravy.",
    pairing: "Pap, if you know you know.",
    colors: ["#E3B23C", "#22333B"], pattern: "plain",
  },
  {
    id: "ayam-sardine", brand: "Ayam Brand", name: "Sardines in Tomato Sauce", iconic: true,
    species: "sardine", cc: "MY", medium: "tomato sauce", price: 1,
    tags: ["classic", "bright"],
    note: "The rooster tin, founded in Singapore in 1892 — Southeast Asia's definition of canned sardines.",
    pairing: "Steamed rice and fried shallots.",
    colors: ["#C0392B", "#F4E8D0"], pattern: "dots",
  },
  {
    id: "five55-sardine", brand: "555", name: "Sardines in Tomato Sauce",
    species: "sardine", cc: "PH", medium: "tomato sauce", price: 1,
    tags: ["classic", "bright"],
    note: "The Philippines' breakfast of champions — sardinas with rice, any day ending in 'y'.",
    pairing: "Garlic rice and a fried egg.",
    colors: ["#2B5C8A", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "dongwon-tuna", brand: "Dongwon", name: "Light Tuna", iconic: true,
    species: "tuna", cc: "KR", medium: "water", price: 1,
    tags: ["clean", "classic"],
    note: "Korea's chamchi — the can behind chamchi-jjigae, kimbap, and a thousand dorm-room meals.",
    pairing: "Straight into kimchi stew.",
    colors: ["#C8402A", "#F4E8D0"], pattern: "plain",
  },
  {
    id: "kk-mackerel", brand: "K&K", name: "Smoked Mackerel (Can Tsuma)",
    species: "mackerel", cc: "JP", medium: "smoked, in oil", price: 1,
    tags: ["smoky", "rich"],
    note: "Fatty mackerel smoked over cherry wood — Japan's izakaya snack in a can.",
    pairing: "A cold highball.",
    colors: ["#1E1E24", "#E07856"], pattern: "dots",
  },
  {
    id: "greenseas-tuna", brand: "Greenseas", name: "Tuna in Spring Water",
    species: "tuna", cc: "AU", medium: "spring water", price: 1,
    tags: ["clean", "classic"],
    note: "Australia's pantry default — the tuna of a million tuna-and-corn sandwiches.",
    pairing: "White bread, canned corn, mayo.",
    colors: ["#4A7A4F", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "sealord-tuna", brand: "Sealord", name: "Tuna in Spring Water",
    species: "tuna", cc: "NZ", medium: "spring water", price: 1,
    tags: ["clean", "classic"],
    note: "New Zealand's own — from one of the southern hemisphere's great fishing fleets.",
    pairing: "A beach picnic at the bach.",
    colors: ["#2B5C8A", "#F4E8D0"], pattern: "waves",
  },
  {
    id: "jose-octopus", brand: "José Gourmet", name: "Octopus in Olive Oil",
    species: "octopus", cc: "PT", medium: "olive oil", price: 2,
    tags: ["rich", "delicate"],
    note: "Lisbon's design house does pulpo — tender coins in golden oil, gallery-worthy label included.",
    pairing: "Paprika, potatoes, toothpicks.",
    colors: ["#F1E5C8", "#7A2E3A"], pattern: "dots",
  },
  {
    id: "atimanel-mackerel", brand: "Ati Manel", name: "Mackerel Fillets in Olive Oil",
    species: "mackerel", cc: "PT", medium: "olive oil", price: 2,
    tags: ["rich", "clean"],
    note: "Cavala from the revived 1922 cannery — rich fillets that convert mackerel skeptics.",
    pairing: "Rye bread and pickled onion.",
    colors: ["#2E6E63", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "angelo-parodi", brand: "Angelo Parodi", name: "Sardines in Olive Oil",
    species: "sardine", cc: "PT", medium: "olive oil", price: 2,
    tags: ["classic", "rich"],
    note: "The Italian-named, Portuguese-made cult tin — packed by Pinhais, prized by tin hunters.",
    pairing: "Buttered bread and a cold white.",
    colors: ["#1F3A5F", "#E8B54A"], pattern: "plain",
  },
  {
    id: "gueyumar-tuna", brand: "Güeyu Mar", name: "Chargrilled Tuna",
    species: "tuna", cc: "ES", medium: "olive oil", price: 3,
    tags: ["smoky", "decadent"],
    note: "Abel Álvarez's birchwood grill meets bluefin — the steak of the conservas world.",
    pairing: "Good bread, great olive oil.",
    colors: ["#2B2B2B", "#E8B54A"], pattern: "waves",
  },
  {
    id: "ramonpena-mussels", brand: "Ramón Peña", name: "Mussels in Escabeche",
    species: "mussel", cc: "ES", medium: "escabeche", price: 2,
    tags: ["bright", "briny"],
    note: "The gold-standard escabeche — plump mussels in paprika'd vinegar, black-and-gold label.",
    pairing: "Chips and vermouth.",
    colors: ["#1E1E24", "#7FA8C9"], pattern: "stripes",
  },
  {
    id: "donbocarte-anchovy", brand: "Don Bocarte", name: "Anchovies in Olive Oil", iconic: true,
    species: "anchovy", cc: "ES", medium: "olive oil", price: 2,
    tags: ["briny", "delicate"],
    note: "Santoña's benchmark — spring-caught, long-cured, filleted by hand. The anchovy that converts people.",
    pairing: "Tomato bread and cold txakoli.",
    colors: ["#F1E5C8", "#1F3A5F"], pattern: "plain",
  },
  {
    id: "olasagasti-bonito", brand: "Olasagasti", name: "Bonito del Norte in Olive Oil",
    species: "tuna", cc: "ES", medium: "olive oil", price: 2,
    tags: ["clean", "delicate"],
    note: "Getaria's white tuna, line-caught in the Bay of Biscay — silken and mild.",
    pairing: "A pintxo with piquillo pepper.",
    colors: ["#2B5C8A", "#E8B54A"], pattern: "stripes",
  },
  {
    id: "ardearte-sardine", brand: "Ar de Arte", name: "Small Sardines in Olive Oil",
    species: "sardine", cc: "ES", medium: "olive oil", price: 3,
    tags: ["delicate", "clean"],
    note: "New-wave Galician conservas with gallery-grade labels — tiny sardinillas, big flavor.",
    pairing: "Kettle chips and fino.",
    colors: ["#E07856", "#22333B"], pattern: "waves",
  },
  {
    id: "cambados-angulas", brand: "Conservas de Cambados", name: "Baby Eels in Olive Oil (Angulas)", iconic: true,
    species: "eel", cc: "ES", medium: "olive oil", price: 3,
    tags: ["decadent", "delicate"],
    note: "Spain's most luxurious tin — glass eels in garlic-infused oil, traditionally eaten with a wooden fork.",
    pairing: "Garlic, chili, cava — wooden fork optional.",
    colors: ["#22333B", "#D9A441"], pattern: "plain",
  },
  {
    id: "labelleiloise-mackerel", brand: "La Belle-Iloise", name: "Mackerel Fillets in White Wine",
    species: "mackerel", cc: "FR", medium: "white wine", price: 2,
    tags: ["delicate", "bright"],
    note: "Quiberon's take on maquereau au vin blanc — gentle, aromatic, very Breton.",
    pairing: "Boiled potatoes and butter.",
    colors: ["#B43A2E", "#F4E8D0"], pattern: "waves",
  },
  {
    id: "campisi-tuna", brand: "Campisi", name: "Tuna in Olive Oil",
    species: "tuna", cc: "IT", medium: "olive oil", price: 2,
    tags: ["rich", "classic"],
    note: "From Marzamemi, Sicily's tuna village — rosy fillets with real depth.",
    pairing: "Pane cunzato with tomatoes.",
    colors: ["#C0392B", "#F4E8D0"], pattern: "plain",
  },
  {
    id: "fish4ever-sardine", brand: "Fish4Ever", name: "Sardines in Olive Oil",
    species: "sardine", cc: "UK", medium: "olive oil", price: 2,
    tags: ["clean", "classic"],
    note: "Sustainably caught Cornish sardines from the UK's conscience-first canner.",
    pairing: "Toast and a squeeze of lemon.",
    colors: ["#2E6E63", "#F4E8D0"], pattern: "dots",
  },
  {
    id: "patagonia-sardine", brand: "Patagonia Provisions", name: "Sardines in Olive Oil",
    species: "sardine", cc: "US", medium: "olive oil", price: 2,
    tags: ["classic", "clean"],
    note: "Cornish sardines, American mission — the tin that proselytizes responsible fishing.",
    pairing: "Crackers by a campfire.",
    colors: ["#D97B3A", "#22333B"], pattern: "stripes",
  },
  {
    id: "wildplanet-sardine", brand: "Wild Planet", name: "Sardines in Extra Virgin Olive Oil",
    species: "sardine", cc: "US", medium: "olive oil", price: 1,
    tags: ["clean", "classic"],
    note: "Pacific sardines, sustainably caught — the gateway tin of American grocery aisles.",
    pairing: "Toast and hot sauce.",
    colors: ["#4A7A4F", "#F4E8D0"], pattern: "waves",
  },
  {
    id: "kk-sardine", brand: "K&K", name: "Japanese Sardines in Olive Oil",
    species: "sardine", cc: "JP", medium: "olive oil", price: 1,
    tags: ["clean", "delicate"],
    note: "Iwashi from Japanese waters in good olive oil — the quiet achiever of the Can Tsuma line.",
    pairing: "Rice, or a cold beer.",
    colors: ["#1E1E24", "#F4E8D0"], pattern: "stripes",
  },
  {
    id: "century-tuna", brand: "Century Tuna", name: "Tuna Flakes in Oil",
    species: "tuna", cc: "PH", medium: "vegetable oil", price: 1,
    tags: ["classic", "clean"],
    note: "The Philippines' tuna of record — flakes built for pandesal and midnight rice.",
    pairing: "Warm pandesal.",
    colors: ["#C8402A", "#F4E8D0"], pattern: "dots",
  },
  {
    id: "sardina-croatia", brand: "Sardina", name: "Sardines in Olive Oil",
    species: "sardine", cc: "HR", medium: "olive oil", price: 1,
    tags: ["briny", "classic"],
    note: "Adriatic sardines from Postira on the island of Brač — Croatia's island cannery.",
    pairing: "Dalmatian-style: bread, olives, wine.",
    colors: ["#2E5FA3", "#F4E8D0"], pattern: "plain",
  },
];
